### ISSUE TITLE
Android Liveness error

### ISSUE THREAD

**Issue by EddyDunda** [voiceittech/VoiceIt2-React-Native-SDK#3]
Android OS. After success encapsulatedFaceEnrollment i got error when try to make liveness verification.
```
{"message":"Error Getting Liveness Challenge"}
```

**Comment by EddyDunda** [comment]
Update: with "liveness - false" param i have successfully verified my user.

**Comment by hasismaeel5** [comment]
Please try a clean build and runt he app again. We just made a push to the android sdk. let us know if the problem persists. Also, are you running this on an actual device or a simulator?

**Comment by EddyDunda** [comment]
@hasismaeel5, i tested it on real device, i cleaned the build and delete application from device, but unfortunately i still got this error. Also i have some questions:
1. Is it correct that after install application i got screen to allow write system settings.
2. I have a very darkness picture of my camera in your view, i guess you will fix it.

**Comment by EddyDunda** [comment]
Hey @hasismaeel5 , any updates?

**Comment by hasismaeel5** [comment]
Let me look into this today. We were busy solving the ios issue, which we have solved locally for now. WIll come back with Android updates by tomorrow. Thanks for the patience Eddy

**Comment by hasismaeel5** [comment]
Eddy can you please show the code when you call the method from the SDK?

**Comment by hasismaeel5** [comment]
@EddyDunda any progress?

**Comment by EddyDunda** [comment]
@hasismaeel5 , i will try to check this today and reply you, actually i use the same code for iOS and Android:
```
Voiceit.encapsulatedFaceVerification(
  voiceItUserId,
  'en-US',
  true,
  false,
  res => {
    console.log(res, 'Res');
  }
);
```

Today i will try to run package again (new version) and reply you.

**Comment by EddyDunda** [comment]
@hasismaeel5 In 1.0.2 version i can't verify my user in liveness and without liveness mode. Also i need use flash light to correct enrollment and grant some screen for writing settings (https://github.com/voiceittech/VoiceIt2-React-Native-SDK/issues/3#issuecomment-760995080)

Face enrollment without liveness verification:
```
const voiceItUserId = "usr_a87f525d54a04cbc88264aaf32865289";
Voiceit.encapsulatedFaceEnrollment(voiceItUserId, res => {
    Voiceit.encapsulatedFaceVerification(
      voiceItUserId,
      'en-US',
      false,
      false,
      res => {
        console.log(res, 'Res');
      }
    );
  });
```
Result: 
https://user-images.githubusercontent.com/69241200/105844971-b9d62980-5fe2-11eb-8b86-9e35e75842f5.mp4

Face enrollment with liveness verification:
```
const voiceItUserId = "usr_a87f525d54a04cbc88264aaf32865289";
Voiceit.encapsulatedFaceEnrollment(voiceItUserId, res => {
    Voiceit.encapsulatedFaceVerification(
      voiceItUserId,
      'en-US',
      true,
      false,
      res => {
        console.log(res, 'Res');
      }
    );
  });
```
Result:
https://user-images.githubusercontent.com/69241200/105845070-df633300-5fe2-11eb-8e14-34a24f5a14c7.mp4

**Comment by EddyDunda** [comment]
@hasismaeel5 i tried to verify my face on Xiaomi Redmi Note 6 Pro and i got success, but only without liveness mode. With enabled liveness mode i still have this error message - "Error Getting Liveness Challenge"

**Comment by hasismaeel5** [comment]
We just pushed a new Android SDK version, please do a clean build on the android repo of your project.

**Comment by EddyDunda** [comment]
@hasismaeel5 i cleaned my build in android repo and i also reinstalled npm package and cleaned again, but i still have "Error Getting Liveness Challenge" error.

**Comment by hasismaeel5** [comment]
That should not be the case. Can you search for the keyword "2.1.7" in your android project? (your project should be fetching Android SDK 2.1.7)

**Comment by EddyDunda** [comment]
Yes, i found your package in my android folder:
https://monosnap.com/file/xfxwOeopr40uCAqnSjlD6kyqWhxnyg

Also here my logcat logs from first init VoiceIt sdk in react-native:
(Never mind about errors from another libraries, because they don't affect to app)
```
2021-01-26 23:59:48.128 27941-28017/com.mindauth I/ReactNativeJS: 'Initialized', 'VoiceIt'
2021-01-26 23:59:48.160 27941-27941/com.mindauth D/FaceEnrollmentView: Cannot hide action bar
2021-01-26 23:59:48.189 27941-27941/com.mindauth I/Timeline: Timeline: Activity_launch_request time:126441156 intent:Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.packageinstaller (has extras) }
2021-01-26 23:59:48.601 27941-28018/com.mindauth W/System.err: java.io.FileNotFoundException: /data/user/0/com.mindauth/files/SKS_KEY_FILEprofile (No such file or directory)
2021-01-26 23:59:48.601 27941-28018/com.mindauth W/System.err:     at java.io.FileInputStream.open0(Native Method)
2021-01-26 23:59:48.601 27941-28018/com.mindauth W/System.err:     at java.io.FileInputStream.open(FileInputStream.java:231)
2021-01-26 23:59:48.601 27941-28018/com.mindauth W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:165)
2021-01-26 23:59:48.601 27941-28018/com.mindauth W/System.err:     at android.app.ContextImpl.openFileInput(ContextImpl.java:570)
2021-01-26 23:59:48.601 27941-28018/com.mindauth W/System.err:     at android.content.ContextWrapper.openFileInput(ContextWrapper.java:212)
2021-01-26 23:59:48.601 27941-28018/com.mindauth W/System.err:     at android.content.ContextWrapper.openFileInput(ContextWrapper.java:212)
2021-01-26 23:59:48.601 27941-28018/com.mindauth W/System.err:     at com.reactlibrary.securekeystore.Storage.readValues(Storage.java:21)
2021-01-26 23:59:48.601 27941-28018/com.mindauth W/System.err:     at com.reactlibrary.securekeystore.RNSecureKeyStoreModule.getSymmetricKey(RNSecureKeyStoreModule.java:193)
2021-01-26 23:59:48.601 27941-28018/com.mindauth W/System.err:     at com.reactlibrary.securekeystore.RNSecureKeyStoreModule.getPlainText(RNSecureKeyStoreModule.java:198)
2021-01-26 23:59:48.601 27941-28018/com.mindauth W/System.err:     at com.reactlibrary.securekeystore.RNSecureKeyStoreModule.get(RNSecureKeyStoreModule.java:150)
2021-01-26 23:59:48.602 27941-28018/com.mindauth W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-01-26 23:59:48.602 27941-28018/com.mindauth W/System.err:     at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
2021-01-26 23:59:48.602 27941-28018/com.mindauth W/System.err:     at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
2021-01-26 23:59:48.602 27941-28018/com.mindauth W/System.err:     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
2021-01-26 23:59:48.602 27941-28018/com.mindauth W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2021-01-26 23:59:48.602 27941-28018/com.mindauth W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2021-01-26 23:59:48.602 27941-28018/com.mindauth W/System.err:     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
2021-01-26 23:59:48.602 27941-28018/com.mindauth W/System.err:     at android.os.Looper.loop(Looper.java:201)
2021-01-26 23:59:48.602 27941-28018/com.mindauth W/System.err:     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
2021-01-26 23:59:48.602 27941-28018/com.mindauth W/System.err:     at java.lang.Thread.run(Thread.java:764)
2021-01-26 23:59:48.609 27941-28017/com.mindauth I/ReactNativeJS: [Error: {"code":404,"api-level":28,"message":/data/user/0/com.mindauth/files/SKS_KEY_FILEprofile (No such file or directory)}], 'Error'
2021-01-26 23:59:48.614 27941-27941/com.mindauth I/ReactNative: [GESTURE HANDLER] Initialize gesture handler for root view com.facebook.react.ReactRootView{a5a7843 V.E...... .......D 0,0-1080,2192 #1}
2021-01-26 23:59:48.614 27941-28018/com.mindauth W/System.err: java.io.FileNotFoundException: /data/user/0/com.mindauth/files/SKS_KEY_FILETOKEN (No such file or directory)
2021-01-26 23:59:48.615 27941-28018/com.mindauth W/System.err:     at java.io.FileInputStream.open0(Native Method)
2021-01-26 23:59:48.615 27941-28018/com.mindauth W/System.err:     at java.io.FileInputStream.open(FileInputStream.java:231)
2021-01-26 23:59:48.615 27941-28018/com.mindauth W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:165)
2021-01-26 23:59:48.615 27941-28018/com.mindauth W/System.err:     at android.app.ContextImpl.openFileInput(ContextImpl.java:570)
2021-01-26 23:59:48.615 27941-28018/com.mindauth W/System.err:     at android.content.ContextWrapper.openFileInput(ContextWrapper.java:212)
2021-01-26 23:59:48.615 27941-28018/com.mindauth W/System.err:     at android.content.ContextWrapper.openFileInput(ContextWrapper.java:212)
2021-01-26 23:59:48.615 27941-28018/com.mindauth W/System.err:     at com.reactlibrary.securekeystore.Storage.readValues(Storage.java:21)
2021-01-26 23:59:48.615 27941-28018/com.mindauth W/System.err:     at com.reactlibrary.securekeystore.RNSecureKeyStoreModule.getSymmetricKey(RNSecureKeyStoreModule.java:193)
2021-01-26 23:59:48.615 27941-28018/com.mindauth W/System.err:     at com.reactlibrary.securekeystore.RNSecureKeyStoreModule.getPlainText(RNSecureKeyStoreModule.java:198)
2021-01-26 23:59:48.616 27941-28018/com.mindauth W/System.err:     at com.reactlibrary.securekeystore.RNSecureKeyStoreModule.get(RNSecureKeyStoreModule.java:150)
2021-01-26 23:59:48.616 27941-28018/com.mindauth W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2021-01-26 23:59:48.616 27941-28018/com.mindauth W/System.err:     at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
2021-01-26 23:59:48.616 27941-28018/com.mindauth W/System.err:     at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
2021-01-26 23:59:48.616 27941-28018/com.mindauth W/System.err:     at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
2021-01-26 23:59:48.616 27941-28018/com.mindauth W/System.err:     at android.os.Handler.handleCallback(Handler.java:873)
2021-01-26 23:59:48.616 27941-28018/com.mindauth W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2021-01-26 23:59:48.616 27941-28018/com.mindauth W/System.err:     at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
2021-01-26 23:59:48.616 27941-28018/com.mindauth W/System.err:     at android.os.Looper.loop(Looper.java:201)
2021-01-26 23:59:48.616 27941-28018/com.mindauth W/System.err:     at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
2021-01-26 23:59:48.617 27941-28018/com.mindauth W/System.err:     at java.lang.Thread.run(Thread.java:764)
2021-01-26 23:59:49.825 27941-27941/com.mindauth W/DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite.face not found.
2021-01-26 23:59:49.851 27941-27941/com.mindauth I/DynamiteModule: Considering local module com.google.android.gms.vision.dynamite.face:0 and remote module com.google.android.gms.vision.dynamite.face:0
2021-01-26 23:59:49.851 27941-27941/com.mindauth D/FaceNativeHandle: Cannot load feature, fall back to load whole module.
2021-01-26 23:59:49.852 27941-27941/com.mindauth W/DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite not found.
2021-01-26 23:59:49.857 27941-27941/com.mindauth I/DynamiteModule: Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:2703
2021-01-26 23:59:49.857 27941-27941/com.mindauth I/DynamiteModule: Selected remote version of com.google.android.gms.vision.dynamite, version >= 2703
2021-01-26 23:59:49.857 27941-27941/com.mindauth V/DynamiteModule: Dynamite loader version >= 2, using loadModule2NoCrashUtils
2021-01-26 23:59:49.863 27941-27941/com.mindauth I/DynamiteLoaderV2Impl: [71] Dynamitemodulesa
2021-01-26 23:59:49.865 27941-27941/com.mindauth W/com.mindauth: Unsupported class loader
2021-01-26 23:59:49.889 27941-27941/com.mindauth W/DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite.face not found.
2021-01-26 23:59:49.944 27941-27941/com.mindauth I/DynamiteModule: Considering local module com.google.android.gms.vision.face:0 and remote module com.google.android.gms.vision.face:1
2021-01-26 23:59:49.944 27941-27941/com.mindauth I/DynamiteModule: Selected remote version of com.google.android.gms.vision.face, version >= 1
2021-01-26 23:59:49.947 27941-27941/com.mindauth I/DynamiteLoaderV2Impl: [71] VisionFace.optional
2021-01-26 23:59:49.948 27941-27941/com.mindauth W/com.mindauth: Unsupported class loader
2021-01-26 23:59:50.071 27941-27941/com.mindauth W/com.mindauth: Accessing hidden field Ljava/nio/Buffer;->address:J (light greylist, reflection)
2021-01-26 23:59:50.076 27941-27941/com.mindauth I/native: face_detector_v2_jni.cc:33 Loading models/fssd_100_8bit_v1.tflite
2021-01-26 23:59:50.121 27941-27941/com.mindauth I/native: face_detector_v2_jni.cc:33 Loading models/fssd_100_8bit_gray_v1.tflite
2021-01-26 23:59:50.162 27941-27941/com.mindauth I/native: face_detector_v2_jni.cc:33 Loading models/LMprec_600.emd
2021-01-26 23:59:50.173 27941-27941/com.mindauth I/native: face_detector_v2_jni.cc:33 Loading models/BCLlefteyeclosed_200.emd
2021-01-26 23:59:50.173 27941-27941/com.mindauth I/native: face_detector_v2_jni.cc:33 Loading models/BCLrighteyeclosed_200.emd
2021-01-26 23:59:50.174 27941-27941/com.mindauth I/native: face_detector_v2_jni.cc:33 Loading models/BCLjoy_200.emd
2021-01-26 23:59:50.174 27941-27941/com.mindauth I/native: face_detector_v2_jni.cc:33 Loading models/MFT_fssd_accgray.pb
2021-01-26 23:59:50.174 27941-27941/com.mindauth I/native: face_detector_v2_jni.cc:33 Loading models/contours.tfl
2021-01-26 23:59:50.179 27941-27941/com.mindauth I/native: face_detector_v2_jni.cc:33 Loading models/blazeface.tfl
2021-01-26 23:59:50.194 27941-27941/com.mindauth I/tflite: Initialized TensorFlow Lite runtime.
2021-01-26 23:59:50.244 27941-27941/com.mindauth W/com.mindauth: type=1400 audit(0.0:65919): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4952 scontext=u:r:untrusted_app:s0:c47,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
2021-01-26 23:59:50.260 27941-27941/com.mindauth E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2021-01-26 23:59:50.271 27941-27941/com.mindauth E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2021-01-26 23:59:50.254 27941-27941/com.mindauth W/com.mindauth: type=1400 audit(0.0:65920): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4952 scontext=u:r:untrusted_app:s0:c47,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
2021-01-26 23:59:50.292 27941-27941/com.mindauth E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2021-01-26 23:59:50.274 27941-27941/com.mindauth W/com.mindauth: type=1400 audit(0.0:65921): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4952 scontext=u:r:untrusted_app:s0:c47,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
2021-01-26 23:59:50.292 27941-27941/com.mindauth E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2021-01-26 23:59:50.294 27941-27941/com.mindauth E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2021-01-26 23:59:50.284 27941-27941/com.mindauth W/com.mindauth: type=1400 audit(0.0:65923): avc: denied { read } for name="u:object_r:vendor_camera_prop:s0" dev="tmpfs" ino=4952 scontext=u:r:untrusted_app:s0:c47,c257,c512,c768 tcontext=u:object_r:vendor_camera_prop:s0 tclass=file permissive=0
2021-01-26 23:59:50.295 27941-27941/com.mindauth E/libc: Access denied finding property "vendor.camera.hal1.packagelist"
2021-01-26 23:59:50.878 27941-27941/com.mindauth D/Camera: Lct package name is com.mindauth
2021-01-26 23:59:50.879 27941-27941/com.mindauth E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2021-01-26 23:59:50.880 27941-27941/com.mindauth E/libc: Access denied finding property "vendor.camera.aux.packagelist"
2021-01-26 23:59:51.008 27941-27941/com.mindauth W/Activity: Slow Operation: Activity com.mindauth/com.voiceit.voiceit2.FaceEnrollmentView onActivityResult took 1191ms
2021-01-26 23:59:51.254 27941-27941/com.mindauth W/Thread-6: type=1400 audit(0.0:65927): avc: denied { read } for name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=4960 scontext=u:r:untrusted_app:s0:c47,c257,c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
2021-01-26 23:59:51.264 27941-28153/com.mindauth E/libc: Access denied finding property "ro.hardware.chipname"
2021-01-26 23:59:52.006 27941-27941/com.mindauth V/AsyncHttpRH: Progress 158 from 158 (100%)
2021-01-26 23:59:53.405 27941-27965/com.mindauth I/com.mindauth: ProcessProfilingInfo new_methods=6719 is saved saved_to_disk=1 resolve_classes_delay=8000
2021-01-26 23:59:53.835 27941-27941/com.mindauth V/AsyncHttpRH: Progress 162 from 110184 ( 0%)
2021-01-26 23:59:53.836 27941-27941/com.mindauth V/AsyncHttpRH: Progress 364 from 110184 ( 0%)
2021-01-26 23:59:53.836 27941-27941/com.mindauth V/AsyncHttpRH: Progress 4460 from 110184 ( 4%)
2021-01-26 23:59:53.837 27941-27941/com.mindauth V/AsyncHttpRH: Progress 8556 from 110184 ( 8%)
2021-01-26 23:59:53.838 27941-27941/com.mindauth V/AsyncHttpRH: Progress 12652 from 110184 (11%)
2021-01-26 23:59:53.838 27941-27941/com.mindauth V/AsyncHttpRH: Progress 16748 from 110184 (15%)
2021-01-26 23:59:53.839 27941-27941/com.mindauth V/AsyncHttpRH: Progress 20844 from 110184 (19%)
2021-01-26 23:59:53.839 27941-27941/com.mindauth V/AsyncHttpRH: Progress 24940 from 110184 (23%)
2021-01-26 23:59:53.840 27941-27941/com.mindauth V/AsyncHttpRH: Progress 29036 from 110184 (26%)
2021-01-26 23:59:53.841 27941-27941/com.mindauth V/AsyncHttpRH: Progress 33132 from 110184 (30%)
2021-01-26 23:59:53.841 27941-27941/com.mindauth V/AsyncHttpRH: Progress 37228 from 110184 (34%)
2021-01-26 23:59:53.842 27941-27941/com.mindauth V/AsyncHttpRH: Progress 41324 from 110184 (38%)
2021-01-26 23:59:53.843 27941-27941/com.mindauth V/AsyncHttpRH: Progress 45420 from 110184 (41%)
2021-01-26 23:59:53.844 27941-27941/com.mindauth V/AsyncHttpRH: Progress 49516 from 110184 (45%)
2021-01-26 23:59:53.845 27941-27941/com.mindauth V/AsyncHttpRH: Progress 53612 from 110184 (49%)
2021-01-26 23:59:53.845 27941-27941/com.mindauth V/AsyncHttpRH: Progress 57708 from 110184 (52%)
2021-01-26 23:59:53.846 27941-27941/com.mindauth V/AsyncHttpRH: Progress 61804 from 110184 (56%)
2021-01-26 23:59:53.847 27941-27941/com.mindauth V/AsyncHttpRH: Progress 65900 from 110184 (60%)
2021-01-26 23:59:53.848 27941-27941/com.mindauth V/AsyncHttpRH: Progress 69996 from 110184 (64%)
2021-01-26 23:59:53.849 27941-27941/com.mindauth V/AsyncHttpRH: Progress 74092 from 110184 (67%)
2021-01-26 23:59:53.849 27941-27941/com.mindauth V/AsyncHttpRH: Progress 78188 from 110184 (71%)
2021-01-26 23:59:53.850 27941-27941/com.mindauth V/AsyncHttpRH: Progress 82284 from 110184 (75%)
2021-01-26 23:59:53.851 27941-27941/com.mindauth V/AsyncHttpRH: Progress 86380 from 110184 (78%)
2021-01-26 23:59:53.852 27941-27941/com.mindauth V/AsyncHttpRH: Progress 90476 from 110184 (82%)
2021-01-26 23:59:53.853 27941-27941/com.mindauth V/AsyncHttpRH: Progress 94572 from 110184 (86%)
2021-01-26 23:59:53.854 27941-27941/com.mindauth V/AsyncHttpRH: Progress 98668 from 110184 (90%)
2021-01-26 23:59:53.855 27941-27941/com.mindauth V/AsyncHttpRH: Progress 102764 from 110184 (93%)
2021-01-26 23:59:53.856 27941-27941/com.mindauth V/AsyncHttpRH: Progress 106860 from 110184 (97%)
2021-01-26 23:59:53.856 27941-27941/com.mindauth V/AsyncHttpRH: Progress 110146 from 110184 (100%)
2021-01-26 23:59:53.857 27941-27941/com.mindauth V/AsyncHttpRH: Progress 110148 from 110184 (100%)
2021-01-26 23:59:53.858 27941-27941/com.mindauth V/AsyncHttpRH: Progress 110184 from 110184 (100%)
2021-01-26 23:59:55.592 27941-27941/com.mindauth V/AsyncHttpRH: Progress 287 from 287 (100%)
2021-01-26 23:59:56.028 27941-28005/com.mindauth W/ConnectionTracker: Exception thrown while unbinding
    java.lang.IllegalArgumentException: Service not registered: ls@8d37376
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1570)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1702)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:727)
        at ci.f(:com.google.android.gms.dynamite_measurementdynamite@204714065@20.47.14 (100400-0):1)
        at ci.d(:com.google.android.gms.dynamite_measurementdynamite@204714065@20.47.14 (100400-0):2)
        at lt.E(:com.google.android.gms.dynamite_measurementdynamite@204714065@20.47.14 (100400-0):9)
        at ld.a(:com.google.android.gms.dynamite_measurementdynamite@204714065@20.47.14 (100400-0):3)
        at ef.run(:com.google.android.gms.dynamite_measurementdynamite@204714065@20.47.14 (100400-0):3)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at iy.run(:com.google.android.gms.dynamite_measurementdynamite@204714065@20.47.14 (100400-0):5)
2021-01-26 23:59:57.666 27941-28018/com.mindauth I/Timeline: Timeline: Activity_launch_request time:126450633 intent:Intent { cmp=com.mindauth/com.voiceit.voiceit2.FaceVerificationView (has extras) }
2021-01-26 23:59:57.739 27941-27941/com.mindauth D/Camera: app passed NULL surface
2021-01-26 23:59:57.812 27941-27941/com.mindauth W/Activity: Slow Operation: Activity com.mindauth/com.voiceit.voiceit2.FaceEnrollmentView onPause took 165ms
2021-01-26 23:59:57.832 27941-27941/com.mindauth W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@8d17b4e
2021-01-26 23:59:57.857 27941-27941/com.mindauth D/FaceVerificationView: Cannot hide action bar
2021-01-26 23:59:57.879 27941-27941/com.mindauth I/Timeline: Timeline: Activity_launch_request time:126450846 intent:Intent { act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.packageinstaller (has extras) }
2021-01-27 00:00:00.056 27941-27968/com.mindauth D/TransportRuntime.CctTransportBackend: Making request to: https://crashlyticsreports-pa.googleapis.com/v1/firelog/legacy/batchlog
2021-01-27 00:00:00.057 27941-27968/com.mindauth I/DpmTcmClient: RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
2021-01-27 00:00:00.154 27941-27941/com.mindauth V/AsyncHttpRH: Progress 69 from 69 (100%)
2021-01-27 00:00:02.245 27941-27968/com.mindauth I/TransportRuntime.CctTransportBackend: Status Code: 200
2021-01-27 00:00:02.245 27941-27968/com.mindauth I/TransportRuntime.CctTransportBackend: Content-Type: application/json; charset=UTF-8
2021-01-27 00:00:02.246 27941-27968/com.mindauth I/TransportRuntime.CctTransportBackend: Content-Encoding: gzip
2021-01-27 00:00:03.192 27941-28017/com.mindauth I/ReactNativeJS: '{"message":"Error Getting Liveness Challenge"}', 'Ress'
```

**Comment by hasismaeel5** [comment]
@EddyDunda We made another change to the SDK. Pealse use the latest version now, 1.0.3

**Comment by EddyDunda** [comment]
@hasismaeel5 nothing new as for iOS sdk, too. Still have Error Getting Liveness error.

**Comment by hasismaeel5** [comment]
okay let's head to the IOS issue

**Comment by hasismaeel5** [comment]
Hey @EddyDunda are you still having this issue?

**Comment by EddyDunda** [comment]
@hasismaeel5 Hey, yep, still have.

**Comment by EddyDunda** [comment]
@hasismaeel5 Fixed.
Check this issue: https://github.com/voiceittech/VoiceIt2-React-Native-SDK/issues/9#issue-803534139
